source 'https://rubygems.org'
gem 'github-pages'
gem 'jekyll-sitemap'
gem 'jekyll-watch'
gem 'jekyll-archives'
gem 'jekyll-feed'
gem 'jekyll-paginate'
gem 'jekyll-minifier'
gem 'tzinfo-data'
gem 'jekyll-tagging'
gem 'jekyll-redirect-from'
gem 'jekyll-tagging-related_posts'
gem 'concurrent-ruby', "~> 1.1.8"
